# -*- coding: utf-8 -*-
#
# pygtrie documentation build configuration file, created by
# sphinx-quickstart on Tue Feb  4 02:47:23 2014.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# -- General configuration -----------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
needs_sphinx = '9.0'

import ast
import inspect
import os
import re
import sys

# import sphinx.pycode.parser
import sphinx.util.inspect
import sphinx.pycode.ast

sys.path.insert(0, os.getcwd())

# Add any Sphinx extension module names here, as strings. They can be extensions
# coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = ['sphinx.ext.autodoc', 'sphinx.ext.intersphinx',
              'sphinx.ext.viewcode', 'sphinx.ext.napoleon']

# Add any paths that contain templates here, relative to this directory.
templates_path = []

# The suffix of source filenames.
#source_suffix = {'.rst': 'restructuredtext'}

# The encoding of source files.
source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'pygtrie'
copyright = u'2014-2017 by Google LLC; 2018-2026 by Michał Nazarewicz'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#language = ''

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#today = ''
# Else, today_fmt is used as the format for a strftime call.
#today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['README.rst', 'examples/README.rst']

# The reST default role (used for this markup: `text`) to use for all documents.
#default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
add_function_parentheses = False

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
add_module_names = False

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
#modindex_common_prefix = []


# -- Options for HTML output ---------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = 'classic'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#html_theme_options = {}

# Add any paths that contain custom themes here, relative to this directory.
#html_theme_path = []

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
#html_title = None

# A shorter title for the navigation bar.  Default is the same as html_title.
#html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
#html_logo = None

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
#html_favicon = None

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = []

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
#html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
#html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
#html_additional_pages = {}

# If false, no module index is generated.
#html_domain_indices = True

# If false, no index is generated.
#html_use_index = True

# If true, the index is split into individual pages for each letter.
#html_split_index = False

# If true, links to the reST sources are added to the pages.
#html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
#html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
#html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
html_use_opensearch = 'http://pythonhosted.org/pygtrie'

# This is the file name suffix for HTML files (e.g. ".xhtml").
#html_file_suffix = None

# Output file base name for HTML help builder.
htmlhelp_basename = 'pygtriedoc'


# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {'python': ('https://docs.python.org/3', None)}


napoleon_google_docstring = True
napoleon_include_init_with_doc = True
napoleon_include_special_with_doc = True


autodoc_default_options = {
    'member-order': 'bysource',
}
autodoc_preserve_defaults = True


nitpicky = True
nitpick_ignore_regex = (
    (r'py:class', r'^pygtrie\.(?:[KVST]|SupportsKeysAndGetItem)$'),
)


def process_signature(
    app,
    obj_type,
    name,
    obj,
    options,
    signature,
    return_annotation,
):
    if obj_type == 'class' and name == 'pygtrie._Step':
        # Hide _Step’s constructor signature.
        signature = ''

    return signature, return_annotation


# Work-around for <https://github.com/sphinx-doc/sphinx/issues/10351>.
#
# Because of the issue, autodoc-process-signature does not process overloads.
# To work around this issue, we’re monkey-patching a lower level function which
# handles function signatures.
def sphinx_inspect_define_patch(
    kind: inspect._ParameterKind,
    arg: ast.arg,
    code: str,
    *,
    defexpr: ast.expr | None,
) -> inspect.Parameter:
    """Defines a new Parameter and does some cleanups.

    First, it hides sentinels used as default values.  If a default value of
    a parameter is '_SENTINEL', replaces it with '...'.  Further, if the type of
    the parameter has '| _Sentinel', strips it.

    Second, replaces K_contra and V_contra by K and V respectively to simplify
    the documentation.
    """
    if defexpr is None:
        default = inspect.Parameter.empty
    else:
        value = sphinx.pycode.ast.unparse(defexpr, code)
        if value == '_SENTINEL':
            value = '...'
        default = sphinx.util.inspect.DefaultValue(value)

    value = sphinx.pycode.ast.unparse(arg.annotation, code)
    if value:
        value = value.replace(' | ~pygtrie._Sentinel', '')
        value = value.replace('pygtrie._SupportsKeysAndGetItem',
                              'pygtrie.SupportsKeysAndGetItem')
        # Because `slice` isn’t subscriptable (yet) and Sphinx gets confused
        # about `'slice[K, None, None]'`.  Clarify what `K` means there.
        value = value.replace('slice[K, None, None]',
                              'slice[~pygtrie.K, None, None]')
        value = re.sub(r'\b(pygtrie\.[KV])_contra\b', r'\1', value).strip()
    annotation = value or inspect.Parameter.empty

    return inspect.Parameter(
        arg.arg, kind, default=default, annotation=annotation)


sphinx.util.inspect._define = sphinx_inspect_define_patch


def setup(app):
    app.connect('autodoc-process-signature', process_signature)
